"""
Django settings for cfi_backend project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import time
import hmac
import hashlib

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v&=^-f46+s)3g1nw!t(y6a3is%w)pxf1e#oiwwhrsx2dolq#!u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'https://a508-160-113-0-194.ngrok-free.app',
    'https://a508-160-113-0-194.ngrok-free.app/monetbil/notifications',
    'localhost',
    '127.0.0.1',
    'a508-160-113-0-194.ngrok-free.app',
    'https://gloire.hometeacher.cg',
]


# Application definition

INSTALLED_APPS = [
     'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'academique',
    'comptes',
    'etudiant',
    'inscription',
    'paiement',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Doit être en premier
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  

]

ROOT_URLCONF = 'cfi_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
    'https://a508-160-113-0-194.ngrok-free.app',
    'https://e076-102-129-81-158.ngrok-free.app '  # Ajoute ton domaine ou ton adresse ngrok ici
]


SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Stockage en base de données
# Autres options possibles :
# 'django.contrib.sessions.backends.cache'  # Stockage en cache
# 'django.contrib.sessions.backends.signed_cookies'  # Stockage dans les cookies sécurisés
# 'django.contrib.sessions.backends.file'  # Stockage dans des fichiers

SESSION_COOKIE_AGE = 3600  # Expiration après 1 heure (en secondes)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Supprime la session quand l'utilisateur ferme son navigateur


WSGI_APPLICATION = 'cfi_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

#commande de connexion à pgadmin  CLI de cfi_bd :psql -U admin -d cfi_bd -h localhost


DATABASES = {
       'default': {
           'ENGINE': 'django.db.backends.postgresql',
           'NAME': 'cfi_bd',
           'USER': 'admin',
           'PASSWORD': 'admin123',
           'HOST': 'localhost',
           'PORT': '5432',
       }
   }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

INTERNAL_IPS = [
    '127.0.0.1',
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
import os

MEDIA_URL = '/media/'  # URL pour accéder aux fichiers
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Répertoire où les fichiers seront stockés


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration CORS

# Configuration REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        #'rest_framework.permissions.IsAuthenticated',#acces seul aux authentifies
        'rest_framework.permissions.AllowAny',#acces a toute les permissions non sécuriant
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
      'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],

    'DEFAULT_PAGINATION_CLASS': 
    'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),  # Expire après 30 min
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # Expire après 7 jours
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

MONETBIL_SERVICE_KEY = "LqqXHk0XfPaPWuH08gPtYpL4WtGNy7dF"
MONETBIL_NOTIFY_URL = "https://e076-102-129-81-158.ngrok-free.app/monetbil/notifications"
MONETBIL_BASE_URL = "https://api.monetbil.com/payment/v2.1/placePayment"
# Configuration Monetbil
MONETBIL_SECRET_KEY = "RLoDzGvirr5Xikm24fX0EobXjNBmxq8CTqQQL5mByKl0qj66jDveYk8Rf743abSg"   # La clé secrète fournie par 
#  curl -Method POST -Uri "https://api.monetbil.com/payment/v1/placePayment" -Headers @{"Content-Type"="application/json"} -Body '{"service": "LqqXHk0XfPaPWuH08gPtYpL4WtGNy7dF", "phonenumber": "242068503126","country":"CG", "amount": "100", "notify_url": " https://ed33-102-129-75-212.ngrok-free.app /monetbil/notifications"}'
CSRF_TRUSTED_ORIGINS = ['https://e076-102-129-81-158.ngrok-free.app/place_payment/', 'https://e076-102-129-81-158.ngrok-free.app/check_payment/'] # Ajoute l'URL de ton frontend ici.
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = True
CSRF_USE_SESSIONS = False