# Generated by Django 5.1.5 on 2025-01-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id_etudiant', models.AutoField(primary_key=True, serialize=False)),
                ('nom_etudiant', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('pays_naissance', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=10)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id_photo', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_photo', models.CharField(max_length=100)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='etudiant.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Tuteur',
            fields=[
                ('id_tuteur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tuteur', models.CharField(max_length=100)),
                ('prenom_tuteur', models.CharField(max_length=100)),
                ('tel_tuteur', models.CharField(max_length=15)),
                ('email_tuteur', models.EmailField(max_length=254, unique=True)),
                ('nationalite_tuteur', models.CharField(max_length=50)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuteurs', to='etudiant.etudiant')),
            ],
        ),
    ]
