# Generated by Django 5.1.5 on 2025-01-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos_etudiants/'),
        ),
    ]
