# Generated by Django 5.1.5 on 2025-01-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0002_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='prenom_etudiant',
            field=models.CharField(default='shinny', max_length=100),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='mot_de_passe',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='telephone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, null=True, unique=True, upload_to='photos_etudiants/'),
        ),
    ]
