# Generated by Django 5.1.5 on 2025-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0003_etudiant_prenom_etudiant_alter_etudiant_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
