# Generated by Django 5.1.5 on 2025-01-24 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0004_etudiant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteur',
            name='etudiant',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='tuteur',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='etudiant', to='etudiant.tuteur'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
