# Generated by Django 5.1.5 on 2025-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0005_remove_tuteur_etudiant_etudiant_tuteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
