# Generated by Django 5.1.5 on 2025-02-01 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0007_alter_etudiant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer une adresse email valide.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
        migrations.AlterField(
            model_name='tuteur',
            name='email_tuteur',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.RegexValidator(message='Veuillez entrer une adresse email valide.', regex='^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$')]),
        ),
    ]
