# Generated by Django 5.1.5 on 2025-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0010_remove_etudiant_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
