# Generated by Django 5.1.5 on 2025-02-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0011_alter_etudiant_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etudiant',
            old_name='nom_etudiant',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='etudiant',
            old_name='prenom_etudiant',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='tuteur',
            old_name='nom_tuteur',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='tuteur',
            old_name='prenom_tuteur',
            new_name='prenom',
        ),
    ]
