# Generated by Django 5.1.5 on 2025-02-28 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0012_rename_nom_etudiant_etudiant_nom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuteur',
            old_name='email_tuteur',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='tuteur',
            old_name='tel_tuteur',
            new_name='tel',
        ),
    ]
