# Generated by Django 5.1.5 on 2025-02-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0013_rename_email_tuteur_tuteur_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuteur',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
