# Generated by Django 5.1.5 on 2025-04-17 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0014_alter_tuteur_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteur',
            name='nationalite_tuteur',
        ),
    ]
