# Generated by Django 5.1.5 on 2025-04-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0015_remove_tuteur_nationalite_tuteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tuteur',
            name='email',
        ),
    ]
