# Generated by Django 5.1.5 on 2025-04-17 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etudiant', '0016_remove_tuteur_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuteur',
            old_name='nom',
            new_name='tuteur_nom',
        ),
    ]
