# Generated by Django 5.1.5 on 2025-01-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudiant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnneeAcademique',
            fields=[
                ('id_annee_academique', models.AutoField(primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Enregistrement',
            fields=[
                ('id_enregistrement', models.AutoField(primary_key=True, serialize=False)),
                ('date_enregistrement', models.DateField()),
                ('type_enregistrement', models.CharField(choices=[('Inscription', 'Inscription'), ('Reinscription', 'Reinscription')], max_length=15)),
                ('semestre', models.CharField(max_length=20)),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enregistrements', to='inscription.anneeacademique')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enregistrements', to='etudiant.etudiant')),
            ],
        ),
    ]
