# Generated by Django 5.1.5 on 2025-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_alter_enregistrement_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1 (Inscription)'), ('S3', 'Semestre 3 (Réinscription)'), ('S5', 'Semestre 5 (Réinscription)')], max_length=100),
        ),
    ]
