# Generated by Django 5.1.5 on 2025-01-22 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0005_alter_enregistrement_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='semestre',
            field=models.CharField(choices=[('S1', 'Semestre 1'), ('S3', 'Semestre 3'), ('S5', 'Semestre 5')], max_length=50),
        ),
    ]
