# Generated by Django 5.1.5 on 2025-01-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_alter_enregistrement_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='semestre',
            field=models.CharField(choices=[('Semestre 1', 'Semestre 1'), ('Semestre 3', 'Semestre 3'), ('Semestre 5', 'Semestre 5')], max_length=50),
        ),
    ]
