# Generated by Django 5.1.5 on 2025-01-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0008_alter_enregistrement_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='semestre',
            field=models.CharField(choices=[('S1', 'S1 '), ('S3', 'S3 '), ('S5', 'S5 ')], max_length=2),
        ),
    ]
