# Generated by Django 5.1.5 on 2025-01-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_alter_enregistrement_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='anneeacademique',
            name='nom_annee_academique',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5')], max_length=2),
        ),
    ]
