# Generated by Django 5.1.5 on 2025-01-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0010_anneeacademique_nom_annee_academique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6')], max_length=2),
        ),
    ]
