# Generated by Django 5.1.5 on 2025-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0011_alter_enregistrement_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='semestre',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='enregistrement',
            name='type_enregistrement',
            field=models.CharField(max_length=15),
        ),
    ]
