# Generated by Django 5.1.5 on 2025-02-25 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0009_alter_cycle_nom_cycle_alter_mention_nom_filiere_and_more'),
        ('inscription', '0012_alter_enregistrement_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enregistrement',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enregistrements', to='academique.classe'),
        ),
    ]
