# Generated by Django 5.1.5 on 2025-02-27 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0009_alter_cycle_nom_cycle_alter_mention_nom_filiere_and_more'),
        ('etudiant', '0011_alter_etudiant_status'),
        ('inscription', '0013_alter_enregistrement_classe'),
        ('paiement', '0002_alter_facture_numero_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='inscription.anneeacademique')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='academique.classe')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='academique.cycle')),
                ('enregistrement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='inscription.enregistrement')),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='universite', to='etudiant.etudiant')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='paiement.facture')),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='academique.mention')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='academique.niveau')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='paiement.paiement')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='academique.parcours')),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='universite', to='etudiant.photo')),
                ('tuteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universites', to='etudiant.tuteur')),
            ],
        ),
    ]
