# Generated by Django 5.1.5 on 2025-02-27 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0014_universite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='universite',
            name='facture',
        ),
        migrations.RemoveField(
            model_name='universite',
            name='paiement',
        ),
    ]
