# Generated by Django 5.1.5 on 2025-01-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraisPaiement',
            fields=[
                ('id_frais_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('libelle_frais_paiement', models.CharField(max_length=100)),
                ('montant_frais_paiement', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id_facture', models.AutoField(primary_key=True, serialize=False)),
                ('numero_facture', models.CharField(max_length=20)),
                ('date_facture', models.DateField()),
                ('montant_facture', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frais_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='paiement.fraispaiement')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id_paiement', models.AutoField(primary_key=True, serialize=False)),
                ('numero_paiement', models.CharField(max_length=20)),
                ('date_paiement', models.DateField()),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='paiement.facture')),
            ],
        ),
    ]
