# Generated by Django 5.1.5 on 2025-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_alter_facture_numero_facture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentId', models.CharField(max_length=100)),
                ('senderPhone', models.CharField(max_length=20)),
                ('receiverPhone', models.CharField(max_length=20)),
                ('senderOperator', models.CharField(max_length=20)),
                ('receiverOperator', models.CharField(max_length=20)),
                ('senderIndicatif', models.CharField(max_length=5)),
                ('receiverIndicatif', models.CharField(max_length=5)),
                ('amount', models.FloatField()),
                ('transactionStatus', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
