# Generated by Django 5.1.5 on 2025-01-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id_cycle', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cycle', models.CharField(max_length=100)),
                ('libelle_cycle', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id_filiere', models.AutoField(primary_key=True, serialize=False)),
                ('nom_filiere', models.CharField(max_length=100)),
                ('libelle_filiere', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id_niveau', models.AutoField(primary_key=True, serialize=False)),
                ('nom_niveau', models.CharField(max_length=100)),
                ('libelle_niveau', models.TextField()),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux', to='academique.cycle')),
            ],
        ),
        migrations.CreateModel(
            name='Parcours',
            fields=[
                ('id_option', models.AutoField(primary_key=True, serialize=False)),
                ('nom_option', models.CharField(max_length=100)),
                ('libelle_option', models.TextField()),
                ('mention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to='academique.mention')),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id_classe', models.AutoField(primary_key=True, serialize=False)),
                ('nom_classe', models.CharField(max_length=100)),
                ('libelle_classe', models.TextField()),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.niveau')),
                ('parcours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academique.parcours')),
            ],
        ),
    ]
