# Generated by Django 5.1.5 on 2025-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom_classe',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
