# Generated by Django 5.1.5 on 2025-01-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0002_alter_classe_nom_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='nom_cycle',
            field=models.CharField(choices=[('licence', 'Licence'), ('dut', 'DUT'), ('master', 'Master')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='nom_filiere',
            field=models.CharField(choices=[('informatique', 'Informatique'), ('administration', 'Administration')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom_niveau',
            field=models.CharField(choices=[('premiere_annee', 'Première année'), ('deuxieme_annee', 'Deuxième année'), ('troisieme_annee', 'Troisième année'), ('dut1', 'DUT1'), ('dut2', 'DUT2'), ('master1', 'Master1'), ('master2', 'Master2')], max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='nom_option',
            field=models.CharField(choices=[('genie_logiciel', 'Génie logiciel'), ('reseaux_telecommunication', 'Réseaux et télécommunication'), ('systemes_reseaux', 'Systèmes et réseaux'), ('administration_publique', 'Administration publique')], max_length=100, unique=True),
        ),
    ]
