# Generated by Django 5.1.5 on 2025-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0004_alter_cycle_nom_cycle_alter_niveau_nom_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='nom_cycle',
            field=models.CharField(choices=[('licence', 'Licence'), ('dut', 'DUT'), ('master', 'Master')], max_length=100, unique=True),
        ),
    ]
