# Generated by Django 5.1.5 on 2025-01-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0006_alter_niveau_nom_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='capacité',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
