# Generated by Django 5.1.5 on 2025-02-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0008_alter_parcours_nom_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cycle',
            name='nom_cycle',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mention',
            name='nom_filiere',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='niveau',
            name='nom_niveau',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='parcours',
            name='nom_option',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
